-- =====================================================================
-- Migration Script: Move to Three-Database Architecture
-- RAW_DB → STAGING_DB → PRODUCTION_DB
-- Source systems (FieldRoutes, etc.) as schemas
-- =====================================================================

-- Step 1: Create new warehouse (if needed)
-- Note: This might need to be done manually in Snowflake UI
-- CREATE WAREHOUSE IF NOT EXISTS ALTAPESTANALYTICS 
--   WITH WAREHOUSE_SIZE = 'X-SMALL' 
--   AUTO_SUSPEND = 60 
--   AUTO_RESUME = TRUE;

-- Step 2: Create new databases
CREATE DATABASE IF NOT EXISTS RAW_DB;
CREATE DATABASE IF NOT EXISTS STAGING_DB;
CREATE DATABASE IF NOT EXISTS PRODUCTION_DB;

-- Step 3: Create schemas for FieldRoutes in each database
USE DATABASE RAW_DB;
CREATE SCHEMA IF NOT EXISTS FIELDROUTES;

USE DATABASE STAGING_DB;
CREATE SCHEMA IF NOT EXISTS FIELDROUTES;

USE DATABASE PRODUCTION_DB;
CREATE SCHEMA IF NOT EXISTS FIELDROUTES;

-- Step 4: Grant permissions (adjust roles as needed)
GRANT USAGE ON DATABASE RAW_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE STAGING_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE PRODUCTION_DB TO ROLE ACCOUNTADMIN;

GRANT ALL ON SCHEMA RAW_DB.FIELDROUTES TO ROLE ACCOUNTADMIN;
GRANT ALL ON SCHEMA STAGING_DB.FIELDROUTES TO ROLE ACCOUNTADMIN;
GRANT ALL ON SCHEMA PRODUCTION_DB.FIELDROUTES TO ROLE ACCOUNTADMIN;

-- Step 5: Migrate RAW data (from ALTAPEST_DB.RAW.fieldroutes to RAW_DB.FIELDROUTES)
USE DATABASE RAW_DB;
USE SCHEMA FIELDROUTES;

-- Dimension tables
CREATE TABLE IF NOT EXISTS OFFICE_DIM CLONE ALTAPEST_DB.RAW.fieldroutes.OFFICE_DIM;
CREATE TABLE IF NOT EXISTS REGION_DIM CLONE ALTAPEST_DB.RAW.fieldroutes.REGION_DIM;
CREATE TABLE IF NOT EXISTS SERVICETYPE_DIM CLONE ALTAPEST_DB.RAW.fieldroutes.SERVICETYPE_DIM;
CREATE TABLE IF NOT EXISTS CUSTOMERSOURCE_DIM CLONE ALTAPEST_DB.RAW.fieldroutes.CUSTOMERSOURCE_DIM;
CREATE TABLE IF NOT EXISTS GENERICFLAG_DIM CLONE ALTAPEST_DB.RAW.fieldroutes.GENERICFLAG_DIM;
CREATE TABLE IF NOT EXISTS CANCELLATIONREASON_DIM CLONE ALTAPEST_DB.RAW.fieldroutes.CANCELLATIONREASON_DIM;
CREATE TABLE IF NOT EXISTS PRODUCT_DIM CLONE ALTAPEST_DB.RAW.fieldroutes.PRODUCT_DIM;
CREATE TABLE IF NOT EXISTS RESERVICEREASON_DIM CLONE ALTAPEST_DB.RAW.fieldroutes.RESERVICEREASON_DIM;

-- Fact tables
CREATE TABLE IF NOT EXISTS CUSTOMER_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.CUSTOMER_FACT;
CREATE TABLE IF NOT EXISTS EMPLOYEE_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.EMPLOYEE_FACT;
CREATE TABLE IF NOT EXISTS APPOINTMENT_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.APPOINTMENT_FACT;
CREATE TABLE IF NOT EXISTS SUBSCRIPTION_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.SUBSCRIPTION_FACT;
CREATE TABLE IF NOT EXISTS ROUTE_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.ROUTE_FACT;
CREATE TABLE IF NOT EXISTS TICKET_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.TICKET_FACT;
CREATE TABLE IF NOT EXISTS TICKETITEM_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.TICKETITEM_FACT;
CREATE TABLE IF NOT EXISTS PAYMENT_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.PAYMENT_FACT;
CREATE TABLE IF NOT EXISTS APPLIEDPAYMENT_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.APPLIEDPAYMENT_FACT;
CREATE TABLE IF NOT EXISTS NOTE_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.NOTE_FACT;
CREATE TABLE IF NOT EXISTS TASK_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.TASK_FACT;
CREATE TABLE IF NOT EXISTS DOORKNOCK_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.DOORKNOCK_FACT;
CREATE TABLE IF NOT EXISTS CUSTOMERCONTACT_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.CUSTOMERCONTACT_FACT;
CREATE TABLE IF NOT EXISTS CONTRACT_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.CONTRACT_FACT;
CREATE TABLE IF NOT EXISTS CREDITCHARGE_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.CREDITCHARGE_FACT;
CREATE TABLE IF NOT EXISTS CREDITCHARGEITEM_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.CREDITCHARGEITEM_FACT;
CREATE TABLE IF NOT EXISTS CUSTOMERFLAG_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.CUSTOMERFLAG_FACT;
CREATE TABLE IF NOT EXISTS PURCHASEORDER_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.PURCHASEORDER_FACT;
CREATE TABLE IF NOT EXISTS SALE_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.SALE_FACT;
CREATE TABLE IF NOT EXISTS TARGETPEST_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.TARGETPEST_FACT;
CREATE TABLE IF NOT EXISTS UNITTYPE_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.UNITTYPE_FACT;

-- Special tables
CREATE TABLE IF NOT EXISTS CUSTOMERCANCELLATIONREASONS_FACT CLONE ALTAPEST_DB.RAW.fieldroutes.CUSTOMERCANCELLATIONREASONS_FACT;

-- Step 6: Migrate ANALYTICS data (from ALTAPEST_DB.ANALYTICS to STAGING_DB.FIELDROUTES)
USE DATABASE STAGING_DB;
USE SCHEMA FIELDROUTES;

-- Check if ANALYTICS schema exists before trying to clone
CREATE TABLE IF NOT EXISTS DIM_OFFICE AS 
SELECT * FROM ALTAPEST_DB.ANALYTICS.DIM_OFFICE 
WHERE EXISTS (SELECT 1 FROM ALTAPEST_DB.INFORMATION_SCHEMA.TABLES 
              WHERE TABLE_SCHEMA = 'ANALYTICS' AND TABLE_NAME = 'DIM_OFFICE');

CREATE TABLE IF NOT EXISTS DIM_REGION AS 
SELECT * FROM ALTAPEST_DB.ANALYTICS.DIM_REGION
WHERE EXISTS (SELECT 1 FROM ALTAPEST_DB.INFORMATION_SCHEMA.TABLES 
              WHERE TABLE_SCHEMA = 'ANALYTICS' AND TABLE_NAME = 'DIM_REGION');

-- Continue for other tables...

-- Step 7: Create views in PRODUCTION_DB
USE DATABASE PRODUCTION_DB;
USE SCHEMA FIELDROUTES;

-- Core reporting views will be created by running updated SQL scripts

-- Step 8: Update reference tables (office watermarks, etc.)
-- These need to stay in a central location accessible by all databases
USE DATABASE RAW_DB;
CREATE SCHEMA IF NOT EXISTS REF;
USE SCHEMA REF;

-- Clone reference tables if they exist
CREATE TABLE IF NOT EXISTS offices_lookup CLONE ALTAPEST_DB.RAW.REF.offices_lookup;
CREATE TABLE IF NOT EXISTS office_entity_watermark CLONE ALTAPEST_DB.RAW.REF.office_entity_watermark;

-- Step 9: Verify migration
-- Run these queries to confirm data migrated successfully
USE DATABASE RAW_DB;
SELECT 'RAW_DB.FIELDROUTES' as Location, TABLE_NAME, ROW_COUNT 
FROM FIELDROUTES.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

USE DATABASE STAGING_DB;
SELECT 'STAGING_DB.FIELDROUTES' as Location, TABLE_NAME, ROW_COUNT 
FROM FIELDROUTES.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

-- Step 10: After verification, drop old structures (DO THIS CAREFULLY!)
-- DROP SCHEMA IF EXISTS ALTAPEST_DB.RAW CASCADE;
-- DROP SCHEMA IF EXISTS ALTAPEST_DB.ANALYTICS CASCADE;
-- Consider keeping ALTAPEST_DB as archive for a period

-- Notes:
-- 1. CLONE operations are instant and don't copy data (zero-copy cloning)
-- 2. Run this script section by section, verifying each step
-- 3. Update all ETL jobs BEFORE dropping old structures
-- 4. Consider running old and new pipelines in parallel briefly